# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "B101nfo"

# The URL of your site.^
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://llrs.dev/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "If it is code you can copy and reuse (MIT) if it is text, please cite and reuse CC-BY {year}."

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Enable comments by entering your Disqus shortname
disqusShortname = ""

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "hugo-academic"

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true


[outputs]
  home = [ "HTML", "RSS", "JSON",  "WebAppManifest"]
  section = [ "HTML", "RSS" ]
  taxonomy = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"


[permalinks]
  post = "/:year/:month/:slug/"

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"


relativeURLs = true
enableEmoji = true


# To be able to edit posts direclty
[params]
  # add github edit https://bookdown.org/yihui/blogdown/templates.html
  GithubEdit = "https://github.com/llrs/blogR/edit/master/content/"
  GithubSource = "https://github.com/llrs/blogR/blob/master/content/"
  email = "lluis.revilla+blog@gmail.com"
  address = ""
  office_hours = ""
  phone = ""
  skype = ""
  telegram = ""
  twitter = "Lluis_Rev"

  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "python"]
  highlightjsTheme = "github"
  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"

  description = "A bioinformatician blog"
  twitterAuthor = "@Lluis_Rev"
  twitterSite = "b101nfo.blogspot.com"
  color_theme = "default"

# AUTHOR SETUP
# Your details.
name = "Lluís Revilla Sancho"
role = "Bioinformatician"
