[build]
  base = "."
  publish = "public"
  command = "hugo"
[context.production.environment]
  # Also used 0.62
  HUGO_VERSION = "0.91.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
[context.branch-deploy.environment]
  # Also used 0.62
  HUGO_VERSION = "0.91.2"
[context.deploy-preview.environment]
  HUGO_BLOGDOWN_POST_RELREF = "true"
