---
title: A Code of Conduct committee
author: Lluís Revilla Sancho
date: '2025-02-10'
slug: a-code-of-conduct-committee
categories:
  - Bioconductor
tags:
  - R
  - Bioconductor
authors:
  - admin
description: ''
draft: no
editor_options:
  chunk_output_type: console
featured: no
image:
  caption: ''
  focal_point: ''
subtitle: 'Duties of a Code of Conduct committee member'
summary: 'My journey through two years of volunteering for Bioconductor as part of the Code of Conduct.'
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, fig.retina = 2)
```


For the last 2 years I served as part of the Code of Conduct (CoC) committee of Bioconductor. 
I partially served to learn how these committees worked, as it was unclear from outside what they did.
The following is a blog post with my observations and opinions on the Code of Conduct committee (CoCC) I saw. 
This content has been reviewed by the current serving committee. 

## Volunteering

I volunteered after a direct message through Bioconductor slack from the then president of the committee. 
She asked me to serve it as she noted I could be a good candidate. 
I think what moved her was my activity on Bioconductor’s slack. 
The inclusion process is simple, when there are some spots open they open a form to get candidates. 
As a candidate I filled it and waited to see if I was selected.

The form has some basic introduction questions, name, origin, … whether one had read the CoC and a couple of questions related to the CoC: not wrong or right questions but one’s opinion and merits. 
I was unsure what to write on those questions. I
wrote around one short paragraph on those questions.

## Onboarding

Needless to say I got accepted. 
A couple of weeks after finishing the selection process, we had a video call with a couple of people on the CoCC. 
We got a brief introduction on how it works and some internal documentation and files. 

In this onboarding meeting it was highlighted the confidentiality of the work we would take on and which measures we took to reduce the possibility of leaking information. 
It was stressed that we were not the police, we were not supposed to be actively patrolling. 
We should wait and expect the members of the community to come to us. 
However, if we saw something we should raise the issue but our duties didn’t mean looking for incidents actively. 

## Quarterly duties

From then on we meet once a quarter. 
If there were any reports we might replace a scheduled meeting by one about the reported incident. 
Other than that, we would rarely communicate via the private slack channel we had.

The meetings were usually about discussing other cases, or related news or improving the wording of the CoC. 
Some of these meetings were also about the people stepping down and the new elections. 
The serving period is 2 years. People might step off earlier or be candidates for re-election. 
We would also meet around those dates but we kept many interactions asynchronous. 

## On demand duties

During my servicing period we received several communications we had to consider how to resolve. 
Some of them were incidents that people in the community wanted to check in with the CoC to see if a specific person's behavior was within the expected behavior. 
Other were about receiving the CoCC opinion on some matters.

## Out boarding

Two years after my election, once a new election selected the new members I resigned. 
I had the opportunity to be at the introduction meeting of the new members. 
I waited a bit after my period ended but I left without much ceremony or specific recommendations. 

## Other considerations

During the elections of new members, I saw some signs that we looked up for similar traits to those on the committee. 
I think this is especially important when selecting new members that will participate in future decisions. 
But at the same time just because someone came from a different background or with different experience doesn’t make that person better suited for such a committee.

In addition, during the discussions for incidents or cases there were always a few people that voiced their opinions. 
I hardly ever heard of some of them and/or some attended few meetings. 
I think that the CoCC should hear from each one of the members at least if they agree or disagree with a particular position. 
I think that silence in such a committee might not always mean they agree. 
Even if they agree with a given decision they might have a different way to see it that could improve (the wording of) the resolution.

Last and not least, as in any system where there are different independent bodies/boards, the power of the CoCC is enforced by someone else. 
I'm worried because at least once, the CoCC's decisions were not fully implemented. 
Likely due to overlapping or unclear communication or roles.

I hope the Code of Conduct committee continues to help Bioconductor users and beyond. 
